apiVersion: v1
kind: Service
metadata:
  name: mastodon
  labels:
    app: mastodon
spec:
  ports:
    - port: 3000
      name: mastodon-web
    - port: 4000
      name: mastodon-streaming
  selector:
    app: mastodon
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mastodon-pv-system-claim
  labels:
    app: mastodon
spec:
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon
  labels:
    app: mastodon
spec:
  selector:
    matchLabels:
      app: mastodon
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mastodon
        tier: frontend
    spec:
      containers:
      - image: "tootsuite/mastodon:v3.2.1"
        name: mastodon
        env:
        - name: DB_HOST
          value: postgresql
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-pass
              key: password
        ports:
        - containerPort: 3000
          name: mastodon-web
        - containerPort: 4000
          name: mastodon-streaming
        volumeMounts:
        - name: mastodon-system-persistent-storage
          mountPath: /opt/mastodon/public/system
      volumes:
      - name: mastodon-system-persistent-storage
        persistentVolumeClaim:
          claimName: mastodon-pv-system-claim
